# Hexo Configuration
title: 个人博客
description: '个人博客，用于分享技术文章和经验'
author: whitemoker
language: zh-CN

# URL
url: https://whitemoker.github.io/Blog
root: /Blog/
permalink: :title/

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories

# Writing
new_post_name: :title.md
default_layout: post
external_link:
  enable: true

# Extensions
theme: landscape

# TOC Plugin settings
toc:
  enable: true
  class: toc
  list_number: false
  max_depth: 3
  min_depth: 1

# Deployment
deploy:
  type: git
  repo: https://github.com/whitemoker/Blog.git
  branch: gh-pages
